### PR TITLE
WIP: Toyota brake check. 

### PR DESCRIPTION
**Pull request by rbiasini**
safety tests to be done.

### CODE REVIEW

**Comment by geohot** [comment]
We should probably delete safety toyota ipas.

**Comment by rbiasini** [comment]
Ok, can do that. We now have better examples of good angle controls (Nissan)

**Comment by rbiasini** [comment]
@geohot , I can remove the ipas functionality from openpilot as well (30-40 lines), or do you prefer to keep it w/o safety mode?

**Comment by rbiasini** [comment]
This explains and fixes the Lexus CTH inconsistency. 
https://github.com/commaai/opendbc/commit/56f0259dfd59ef072138875d3a0baefd56f411da

Now I can merge this PR.

**Pull request merged**
