### PR TITLE
enable misra-c2012-10.3

### PR DESCRIPTION
**Pull request by 0x41head**
For #1794

### CODE REVIEW

**Comment by 0x41head** [comment]
created PR to fix the bool issue in cppchecker
https://github.com/danmar/cppcheck/pull/5948

**Comment by 0x41head** [comment]
my cppchecker PR has been merged.

**Comment by adeebshihadeh** [comment]
> my cppchecker PR has been merged. @adeebshihadeh

Nice! Can you update the cppcheck version we install to pick up that update? It should be pinned to the commit you got merged.

**Comment by 0x41head** [comment]
Do I submit a new PR for that or can I make the changes in this PR?

**Comment by adeebshihadeh** [comment]
Let's do a separate PR that just updates cppcheck.

**Pull request merged**
