### PR TITLE
Microsecond timer fix

### PR DESCRIPTION
**Pull request by robbederks**
@sshane noticed the microsecond timer is actually running as a half-microsecond timer

### CODE REVIEW

**Comment by robbederks** [comment]
Seems to have been broken by changing the prescaler in https://github.com/commaai/panda/pull/1061

@briskspirit can you double check that you didn't break anything else with that change?

**Comment by briskspirit** [comment]
> Seems to have been broken by changing the prescaler in #1061
> 
> @briskspirit can you double check that you didn't break anything else with that change?

Those values were used for 3 timers only, see no anything else broken.

**Review by briskspirit — APPROVED** [review]

**Comment by robbederks** [comment]
> > Seems to have been broken by changing the prescaler in #1061
> > 
> > @briskspirit can you double check that you didn't break anything else with that change?
> 
> Those values were used for 3 timers only, see no anything else broken.

It's not only the values, in the PR that broke this you changed the APB1 frequency. Are there any other peripherals that could quietly be affected by that change, apart from the microsecond timer?

**Comment by briskspirit** [comment]
By clock configuration map for both F4 and H7 everything else looks good.

**Pull request merged**
