### PR TITLE
Subaru safety param for Impreza/Crosstrek 2020

### PR DESCRIPTION
**Pull request by martinl**
This PR includes following changes:
  - safety parameter for checking Impreza/Crosstrek 2020+ lower steering torque limit
 - safety test covering the new safety parameter

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
This PR is way too big to merge as is. Let's break this up into individual changes.

**Comment by martinl** [comment]
I kept only Impreza/Crosstrek 2020 safety param, other changes get separate PR-s

**Review by jmayes41 — APPROVED** [review]

**Comment by martinl** [comment]
rebased to master

**Comment by martinl** [comment]
Lower torque check is not needed in panda safety since torque scale is same

**Review by jmayes41 — COMMENTED** [review]
Good job guys

**Pull request closed without merging**
