### PR TITLE
Increase Readability, sane CAN IDs, passes throughput tests.

### PR DESCRIPTION
**Pull request by diamondman**
Increase maintainability by splitting up headers.
Change CAN numbering to sequential address space. (0,1,2, not 0,1,4)
Lay foundation for setting canbus speed.

First commit with all later fixes applied, and the problematic USB stack change removed.
Only massive reorganization PR. All other features from the rolled back code can be applied easily on top of this base.

Passes loopback_test and standalone_test.

### CODE REVIEW

**Comment by geohot** [comment]
batman@y840:~/drive/panda/board$ make -f Makefile.legacy 
arm-none-eabi-gcc -g -O0 -Wall -std=gnu90 -mlittle-endian -mthumb -mcpu=cortex-m3 -msoft-float -DSTM32F2 -DSTM32F205xx -I inc -I ../ -nostdlib -fno-builtin -Tstm32_flash.ld "-DALLOW_DEBUG" -o obj/startup_stm32f205xx.o -c startup_stm32f205xx.s
../crypto/getcertheader.py ../certs/debug.pub ../certs/release.pub > obj/cert.h
echo "const uint8_t gitversion[] = \"9ce92549041c3faf32a68c7fbfce2aad9e17d2c6\";" > obj/gitversion.h
arm-none-eabi-gcc -g -O0 -Wall -std=gnu90 -mlittle-endian -mthumb -mcpu=cortex-m3 -msoft-float -DSTM32F2 -DSTM32F205xx -I inc -I ../ -nostdlib -fno-builtin -Tstm32_flash.ld "-DALLOW_DEBUG" -o obj/bootstub.comma.o -c bootstub.c
arm-none-eabi-gcc -g -O0 -Wall -std=gnu90 -mlittle-endian -mthumb -mcpu=cortex-m3 -msoft-float -DSTM32F2 -DSTM32F205xx -I inc -I ../ -nostdlib -fno-builtin -Tstm32_flash.ld "-DALLOW_DEBUG" -o obj/sha.comma.o -c ../crypto/sha.c
arm-none-eabi-gcc -g -O0 -Wall -std=gnu90 -mlittle-endian -mthumb -mcpu=cortex-m3 -msoft-float -DSTM32F2 -DSTM32F205xx -I inc -I ../ -nostdlib -fno-builtin -Tstm32_flash.ld "-DALLOW_DEBUG" -o obj/rsa.comma.o -c ../crypto/rsa.c
arm-none-eabi-gcc -g -O0 -Wall -std=gnu90 -mlittle-endian -mthumb -mcpu=cortex-m3 -msoft-float -DSTM32F2 -DSTM32F205xx -I inc -I ../ -nostdlib -fno-builtin -Tstm32_flash.ld "-DALLOW_DEBUG" -o obj/early.comma.o -c early.c
early.c: In function 'early':
early.c:50:16: warning: unused variable 'i' [-Wunused-variable]
   volatile int i;
                ^
arm-none-eabi-gcc -g -O0 -Wall -std=gnu90 -mlittle-endian -mthumb -mcpu=cortex-m3 -msoft-float -DSTM32F2 -DSTM32F205xx -I inc -I ../ -nostdlib -fno-builtin -Tstm32_flash.ld "-DALLOW_DEBUG" -o obj/llgpio.comma.o -c llgpio.c
arm-none-eabi-gcc -g -O0 -Wall -std=gnu90 -mlittle-endian -mthumb -mcpu=cortex-m3 -msoft-float -DSTM32F2 -DSTM32F205xx -I inc -I ../ -nostdlib -fno-builtin -Tstm32_flash.ld "-DALLOW_DEBUG" -o obj/libc.comma.o -c libc.c
arm-none-eabi-gcc -g -O0 -Wall -std=gnu90 -mlittle-endian -mthumb -mcpu=cortex-m3 -msoft-float -DSTM32F2 -DSTM32F205xx -I inc -I ../ -nostdlib -fno-builtin -Tstm32_flash.ld "-DALLOW_DEBUG" -o obj/bootstub.comma.elf obj/startup_stm32f205xx.o obj/bootstub.comma.o obj/sha.comma.o obj/rsa.comma.o obj/early.comma.o obj/llgpio.comma.o obj/libc.comma.o
/usr/lib/gcc/arm-none-eabi/4.9.3/../../../arm-none-eabi/bin/ld: Warning: alignment 1 of symbol `g_pfnVectors' in obj/startup_stm32f205xx.o is smaller than 4 in obj/early.comma.o
arm-none-eabi-objcopy -v -O binary obj/bootstub.comma.elf obj/bootstub.comma.bin
copy from `obj/bootstub.comma.elf' [elf32-littlearm] to `obj/bootstub.comma.bin' [binary]
arm-none-eabi-gcc -g -O0 -Wall -std=gnu90 -mlittle-endian -mthumb -mcpu=cortex-m3 -msoft-float -DSTM32F2 -DSTM32F205xx -I inc -I ../ -nostdlib -fno-builtin -Tstm32_flash.ld "-DALLOW_DEBUG" -o obj/main.comma.o -c main.c
In file included from main.c:10:0:
usb.h: In function 'usb_setup':
usb.h:379:33: warning: passing argument 1 of 'USB_WritePacket' from incompatible pointer type
                 USB_WritePacket(string_3_desc, min(sizeof(string_3_desc), setup.b.wLength.w), 0);
                                 ^
usb.h:222:6: note: expected 'const uint8_t *' but argument is of type 'uint16_t *'
 void USB_WritePacket(const uint8_t *src, uint16_t len, uint32_t ep) {
      ^
usb.h:295:7: warning: unused variable 'i' [-Wunused-variable]
   int i;
       ^
arm-none-eabi-gcc -g -O0 -Wall -std=gnu90 -mlittle-endian -mthumb -mcpu=cortex-m3 -msoft-float -DSTM32F2 -DSTM32F205xx -I inc -I ../ -nostdlib -fno-builtin -Tstm32_flash.ld "-DALLOW_DEBUG" -o obj/can.comma.o -c can.c
arm-none-eabi-gcc -g -O0 -Wall -std=gnu90 -mlittle-endian -mthumb -mcpu=cortex-m3 -msoft-float -DSTM32F2 -DSTM32F205xx -I inc -I ../ -nostdlib -fno-builtin -Tstm32_flash.ld "-DALLOW_DEBUG" -o obj/uart.comma.o -c uart.c
arm-none-eabi-gcc -g -O0 -Wall -std=gnu90 -mlittle-endian -mthumb -mcpu=cortex-m3 -msoft-float -DSTM32F2 -DSTM32F205xx -I inc -I ../ -nostdlib -fno-builtin -Tstm32_flash.ld "-DALLOW_DEBUG" -o obj/gpio.comma.o -c gpio.c
gpio.c: In function 'set_can_mode':
gpio.c:119:36: error: 'GPIO_AF11_CAN3' undeclared (first use in this function)
       set_gpio_alternate(GPIOB, 3, GPIO_AF11_CAN3);
                                    ^
gpio.c:119:36: note: each undeclared identifier is reported only once for each function it appears in
build.mk:73: recipe for target 'obj/gpio.comma.o' failed
make: *** [obj/gpio.comma.o] Error 1

**Comment by diamondman** [comment]
@geohot Good catch. Fixed. Testing on NEO before pushing fix.

**Comment by geohot** [comment]
Testing on NEO, it doesn't work with MOCK=1 ./boardd.py while master does. Clearly this is not just a style change, as if it were, the code would have the same behavior, which it does not.

Can we go back to headers instead of this? This change was unnecessary and causes build time to be 5x longer on the phone because it has to call into the compiler so many more times. It also makes this diff hard for me to read, you can't mix 1000 line style changes with functionality changes. It's still not working and it's difficult for me to see why.

**Comment by geohot** [comment]
Or if you really insist on breaking things into header and c files, this has to be done in it's own pull request, which changes no functionality but only does that transformation.

**Comment by diamondman** [comment]
Changes abandoned, important pieces applied to existing master.

**Pull request closed without merging**
