### PR TITLE
Subaru legacy safety update

### PR DESCRIPTION
**Pull request by martinl**
Subaru legacy changes:
  - change driver torque to match global
  - brake threshold increased to 2, filter out sensor noise (https://github.com/martinl/openpilot/issues/27)
  - safety parameter for Outback 2018-2019 and Forester 2017-2018 flipped driver torque signal
  - safety tests covering each change

Matching changes on openpilot side are already upstreamed (dashcam only)

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
Should we split out the legacy safety into its own file?

**Comment by adeebshihadeh** [comment]
I split up the legacy safety into its own file. Can you rebase?

**Comment by martinl** [comment]
tests passed, ready for review

**Comment by martinl** [comment]
I cleaned up the commits and rebased, will debug more to find out why the outback preglobal replay test is failing after rebase

**Comment by adeebshihadeh** [comment]
If this is still relevant, can you open smaller PRs to address each thing?

**Pull request closed without merging**
