### PR TITLE
Misra safety Check

### PR DESCRIPTION
**Pull request by bongbui321**
For first part of [#1770](https://github.com/commaai/panda/issues/1770), 
add misra testing for safety files, enable `misra-c2012-10.4`

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
Is this still a draft? If not, I'm not sure what it's supposed to do. The test already checks the safety files. Let me know if you need clarification on the issue.

**Comment by bongbui321** [comment]
Yeah, so right now one of the test in `./test_mutation.py` is failing - it doesn't show on GHA(not sure why), but right now I'm going to enable `misrac-10.4` so that that test would pass and then the first part (board/safety/* files) will be done

**Comment by bongbui321** [comment]
@adeebshihadeh Okay it is ready for review now, enable misrac 10.4 and all the tests `./test_mutation.py` pass now

**Comment by adeebshihadeh** [comment]
@bongbui321 looks like there's a few different things going on in this PR that should be their own PR
* editing test_misra.sh
* adding new mutation test cases
* enabling 10.4

I also formalized the bounty and wrote more instructions on enabling the rest of the MISRA rules: https://github.com/commaai/panda/issues/1794. There's probably a bunch of low hanging fruit in there, along with some tricky ones.

**Pull request closed without merging**
