### PR TITLE
Toyota: limit using driver torque

### PR DESCRIPTION
**Pull request by sshane**
Will verify all cars have similar driver torque scales, but shouldn't need an EPS factor

### CODE REVIEW

**Comment by rbiasini** [comment]
Just totally out of curiosity: is the check on driver torque preferred over motor torque comparison?
Check on motor torque seems a bit more comprehensive, as it might include discrepancies between commanded and actual that are unrelated to the steer torque applied by the driver.

**Comment by sshane** [comment]
Yeah, I'm not too sure if this is a huge improvement now. Originally I believed that the motor torque limit was causing loss of control on turns when hitting bumps, as that would limit torque when the driver isn't touching the wheel, but with good tuning I haven't really seen any issues with lack of control in normal turns.

The two torque limiting methods are enforcing different things though, with most of our brands using the driver torque limits. The driver torque limits solely enforces that the user can easily and safely take over without the wheel fighting them, while the motor torque limits enforces overriding as well as making sure the commanded torque is close to the already applied EPS torque. Which, under normal scenarios the ramp limits should take care of. If the motor isn't responding to our torque commands then it sounds like we have another problem.

It's worth exploring more though, and I'll definitely look at data and segments before any other work is done. What do you think @rbiasini?

**Comment by rbiasini** [comment]
> Originally I believed that the motor torque limit was causing loss of control on turns when hitting bumps, as that would limit torque when the driver isn't touching the wheel, but with good tuning I haven't really seen any of these issues recently.

mmm... putting torque motor and torque cmd on the same plot should tell you if this is the case. Definitely not ideal if torque drop happens due to unexpected discrepancies between the 2 torques, regardless the tuning.

> with most of our brands using the driver torque limits

yeah, motor_torque isn't available on all brands. :) Or maybe it is?

> while the motor torque limits enforces overriding as well as making sure the commanded torque is close to the already applied EPS torque

Exactly

> Which, under normal scenarios I believe the ramp limits should take care of this. If the motor isn't responding to our torque commands then it sounds like we have another problem.

It's a very remote scenario, but imagine that the EPS is not responding to the commanded torque: the controller would wind up the command to the max allowed value in case safety is enforced based on the driver's torque (assume it's 0). Then, if all of a sudden the EPS starts responding again, then the rate limit might be violated. The check on the diff between motor torque and commanded torque would catch this by disallowing the commanded torque to wind up.

Personal 2 cents: the check on driver's torque is good. The check on motor torque is a bit more comprehensive. A third over complex option is to enforce both.

**Comment by sshane** [comment]
Thanks for the reply! Yeah, I suspected we might not be using the motor torque limiter on other brands because a lack of motor signal.

> Definitely not ideal if torque drop happens due to unexpected discrepancies between the 2 torques, regardless the tuning.

I think this is definitely possible in some situations, where we aren't able to apply the desired torque because of mismatched EPS scaling or hitting bumps/potholes, lag in the EPS or signal, etc., but I'm now not convinced I'm hitting it very often, perhaps it was worse with a bad PID tune that constantly overshot.

I do think that having this driver torque blending limiter also implicitly check we don't exceed the effective torque rate limits due to the rare case the EPS isn't responding to our commands isn't the clearest way to do that, when none of the other makes do this (except one), so maybe there can be some other method implemented in the future that ensures we don't limit torque when we don't need to.

For now, I'll close this unless I find some cases where we're significantly limiting torque for no reason.

**Pull request closed without merging**
