### PR TITLE
test bumping ref to see if it fails pipelines

### PR DESCRIPTION
**Pull request by devtekve**

### CODE REVIEW

**Comment by sunnyhaibin** [comment]
```bash
#16 2.626 Traceback (most recent call last):
#16 2.626   File "/tmp/opendbc_repo/opendbc/dbc/generator/tesla/tesla_radar_continental.py", line 4, in <module>
#16 2.626     from opendbc.dbc.generator.tesla._radar_common import get_radar_point_definition, get_val_definition
#16 2.626 ModuleNotFoundError: No module named 'opendbc'
```

**Comment by sunnyhaibin** [comment]
Broken if using this ref: https://github.com/commaai/opendbc/commit/551081b32f4c1a76537ad2c777571ef5b93a849c
Working if using this ref: https://github.com/commaai/opendbc/commit/fb6ad760cce11efc21abc37bafa6e3013dc79797

cc @sshane

**Comment by devtekve** [comment]
Yeah can confirm 551081b32f4c1a76537ad2c777571ef5b93a849c is no longer compatible with Panda

**Comment by devtekve** [comment]
resolved by https://github.com/commaai/panda/pull/2103

**Pull request closed without merging**
