### PR TITLE
Mazda: Fix CX-5 ignition

### PR DESCRIPTION
**Pull request by Jafaral**
Signed-off-by: Jafar Al-Gharaibeh <to.jafar@gmail.com>

### CODE REVIEW

**Comment by Jafaral** [comment]
Now that we allow 0 and 1  for the LSB, maybe we should just shift  right by an additional bit and test for value `0x6U`. thoughts @adeebshihadeh  ?

**Comment by adeebshihadeh** [comment]
Sounds good to me. For CAN ignition cars, we want to make sure the ignition is unique to the brand (to prevent collisions) and generic across the brand. Right now, there's a low cost to changing the signal since there are relatively few users, but it gets harder as the brand grows. I'd like to get this right while the cost is low.

Do we know what this signal is? Can we identify other potential signals that might work?

**Comment by Jafaral** [comment]
I don't know what the message is, but All  supported Mazda cars has it. The MSB is set when ignition is on in CX-5 and CX-9 at least. I did see data from Mazda 3 and it seems to have the same behavior. but the CAN logs are a bit late to see if the bit was zero before ignition, at least from a couple of drives from cars that use the old ignition wiring.  In this PR we test 3 bits. I noticed the second byte is always zero, we can make that as an additional test to reduce the likelihood of collisions.

**Comment by Jafaral** [comment]
@adeebshihadeh, this PR doesn't change the exiting logic, well,  beyond dropping a single bit from the test. This fixes ignition for CX-5 which happens to be the car with most users. Let us get this in for now, and I will collect more data over time on how to proceed if we decide to change.

**Pull request merged**
