### PR TITLE
VW MQB: Updated message and signal data, round 1

### PR DESCRIPTION
**Pull request by jyoung8607**
**Diff reduction with the VW Community Port**

Match commaai/opendbc#357 with improved and mostly-canonical message naming, signal naming, and scaling properties for LH_EPS_03 (formerly known as EPS_01).

**Verification**

Null effective change; renaming only.

**Merge Review**

Getting CI to pass prior to merge might not be possible due to cross-dependencies between opendbc, panda, and openpilot.

### CODE REVIEW

**Comment by robbederks** [comment]
Fixed the naming of the torque signal, but that wasn't enough to make the tests pass again.
If possible, it'd be nice to get this fixed and merged asap, since the opendbc changes are already merged, so the tests on panda master are broken atm

**Comment by jyoung8607** [comment]
Thanks for spotting an issue there, I tweaked the fix to draw direction from the right place.

Certainly having panda and opendbc out of sync is not ideal, but the CI breakage appears unrelated to this change. I think @adeebshihadeh was working on it in panda/bump-openpilot.

**Comment by dnoermann** [comment]
Cool Project that you do.
I saw you implemented Checksum validation for some MQB Can Id's in volkswagen_mqb_get_counter
The Table is the key here , do you probably have the Table for ACC_05 Message available ?
Thanks

**Comment by jyoung8607** [comment]
> Cool Project that you do.
> I saw you implemented Checksum validation for some MQB Can Id's in volkswagen_mqb_get_counter
> The Table is the key here , do you probably have the Table for ACC_05 Message available ?
> Thanks

@dnoermann, I don't have an ACC_05 message on record at all. What are you trying to do?

Since this isn't related to the PR, it would be easiest to discuss if you ask in comma's Discord in #volkswagen-audi.

**Pull request merged**
