### PR TITLE
Implement WebUSB and upgrade WinUSB to 2.0

### PR DESCRIPTION
**Pull request by chrisinajar**
Closes: #103 

Add a Binary Object Store (BOS) descriptor to the USB driver code. Adds WebUSB descriptors and also WinUSB 2.0 (we currently only support 1.0, which is dominantly used on Windows XP).

I left lots of comments as to where I got most of the information / constants / spec descriptions.

* [x] works on osx
* [x] works on eon
* [x] works on pandajs
* [x] works on pandajs over wifi
* [x] works on windows
* [x] un-breaks SPI communications

### CODE REVIEW

**Comment by chrisinajar** [comment]
Also exposes string configuration name, upgrades USB support value from 2.0 to 2.1. Also changes the name from "panda" to "Panda" because it looks a lot better, we should make sure that change doesn't break anything.

Tested and working on white panda, haven't tested on grey yet.
image

**Comment by chrisinajar** [comment]
I believe this is ready now.

**Comment by lomal788** [comment]
i have a same issues if i firmware upgrade my panda and use zadig to install web-usb and it will work fine?
is this version released on 1.5.2?

https://github.com/commaai/panda-artifacts

**Comment by robbederks** [comment]
@lomal788 This has been implemented for a very long time, so yes, 1.5.2 should have it!

**Pull request merged**
