### PR TITLE
safety replay: safety tick

### PR DESCRIPTION
**Pull request by sshane**
similar to test_models

### CODE REVIEW

**Comment by sshane** [comment]
@robbederks this PR causes those blocked message in safety replay

**Comment by robbederks** [comment]
> @robbederks this PR causes those blocked message in safety replay

Which blocked messages?

**Comment by sshane** [comment]
```
TX
total openpilot msgs: 6103
total msgs with controls allowed: 0
blocked msgs: 4978
blocked with controls allowed: 0
blocked addrs: Counter({1160: 4978})
```

before there were messages with controls allowed

**Comment by adeebshihadeh** [comment]
Any reason this isn't merged yet? The tests are passing.

**Comment by sshane** [comment]
The tests aren't great. This would set controls allowed to False if this triggered, and safety replay asserts no messages are blocked while controls allowed... Manually checking the replay results is how I found the Tesla bug, which test_models also would've caught if it weren't for dashcam mode (https://github.com/commaai/panda/pull/1374). I'll ad somethin like test_models's `addr_checks_valid` and should be good to merge

**Pull request merged**
