### PR TITLE
Add Travis badge to README

### PR DESCRIPTION
**Pull request by gliptak**

### CODE REVIEW

**Comment by geohot** [comment]
Will merge once it's green!

**Comment by geohot** [comment]
You know if there's a way to cache the ESP compiler build?

**Comment by geohot** [comment]
btw, the fix for the building was changing the Makefile target

proxy-0000 is old, use user1.bin

https://github.com/commaai/panda/commit/ec237d145db5bc807b7544a0c1b34b35fa095d90

**Comment by gliptak** [comment]
@geohot I see.

For Travis caching https://docs.travis-ci.com/user/caching/#Caching-directories-(Bundler%2C-dependencies)

```
cache:
  directories:
  - .autoconf
  - $HOME/.m2
```
it is unclear how this above interacts with the ```git clone``` ...

**Pull request merged**
