### PR TITLE
Feature/j2534 windows driver

### PR DESCRIPTION
**Pull request by diamondman**
Windows Panda driver, ECU Simulator, J2534 driver, and lots of tests.
J2534 driver supports CAN and ISO15765 protocols.

### CODE REVIEW

**Comment by diamondman** [comment]
Installer needs to be updated to provide the VS runtime requirements.
INF install on windows 7 gives weird errors. Looking for consistent fix.

**Comment by douglasloeb3d** [comment]
I built the driver successfully in win10 with VS2015 Community, WDK and SDK. The driver installs without errors, but the panda shows up only as a hidden device in device manager. I disables driver signing and that didnt work either. 

Looking at the driver properties, driver name still states oem48.inf.



driver_1
driver_2

**Comment by diamondman** [comment]
@douglasloeb3d The inf file being renamed to OEMxx.inf is standard.
01_device_inf_detail
02_devcon_result

Your event log looks very similar to mine.
03_device_events

Did you disable driver signing, uninstall the driver, and reinstall the driver? Not sure what driver signing might do. Also, are you by any chance on a 32 bit windows? I remember reading that driver signing is not as strict on that platform for some reason.

**Comment by douglasloeb3d** [comment]
I installed with out disabling driver signing, and it worked with out issue. I then disabled driver signing and reinstalled. same thing. 

I am going to delete the current devices, reboot and try again.  

are you on win10 as well?

**Comment by diamondman** [comment]
I am using win 10 x64 (and am doing tests on a Win 7 x64 on the side).
So you are saying that it works now? 
One thing to note if you are deleting the device, make sure you delete the device, unplug the panda, plug it back in, and delete the device if it reappears. When I was messing with the drier earlier, it was easy to accidentally install the driver 2+ times, and every time you delete the device and remove the files, it only removes one of them.

**Comment by diamondman** [comment]
First test installer: https://drive.google.com/file/d/0B-3TcOcsIuTMN0xEMWJwYjJ3eVU/view?usp=sharing built from c6aa4fc.

**Comment by douglasloeb3d** [comment]
Still not working, that was built on my machine at work. I will build at home tonight and test again. 
thanks for getting this going though, I really want to get the panda to play nice with my ARM7 based linux computer, but windows driver+virtualbox is what I am trying to get working now.

**Comment by douglasloeb3d** [comment]
I just used your driver that you shared, and I get the same result. Seems like the host thinks the panda is disconnected. Also the driver seems to be install-able without disabling driver signing.

**Comment by diamondman** [comment]
I have had a someone else report that they didn't need to deal with the signatures, the only thing I could think of that would require me to use it is that I have disk encryption on.
I will move this conversation to slack so we can try to resolve it quicker.

**Comment by geohot** [comment]
This week I should have time to work on this! Sorry it's taken so long.

My plan is to test it with Toyota TIS, and once that works, we'll get it upstreamed.

**Comment by TheMutley** [comment]
Can test with GM equivalent , GDS2 whenever it's ready

**Comment by gregjhogan** [comment]
On Win10x64 there is no way this installs without disabling driver signing being required, correct?

Looks like the package is using test signing, so this is a way to disable it (requires UEFI disabled and reboot):
```
Bcdedit.exe -set TESTSIGNING ON
```

I just tried the test installer without disabling the driver signing requirement and it said it succeeded, but I found this error in the log:
```
Adding the driver package failed: A problem was encountered while attempting to add the driver to the store
```

**Comment by gregjhogan** [comment]
I got it to install successfully on Win10x64 by doing the following:
1. open cmd prompt as admin
2. run `bcdedit.exe -set TESTSIGNING ON`
3. reboot
4. install driver using above test installer
    (should prompt you if you want to install an unsigned driver)

I can then open DrewTech's J2534-1 Bus Analysis Tool and connect to the panda

I am also able to use live cabana once I additionally:
1. open [chrome://flags](chrome://flags) and enable:
    * Experimental Web Platform features
    * WebUSB
2. relaunch chrome

I think some people might be getting thrown off by the fact that the installer says it succeeds when you don't have requiring driver signing disabled (because it actually fails to install)

**Comment by gregjhogan** [comment]
I tried firing up the DrewTech tool mentioned in the README.md and it connects successfully, but I don't see any CAN bus messages.  What should work in the DrewTech tool?

Also, when I disconnect I get this error:
```
Faulting application name: DrewTech_J2534-1.exe, version: 1.7.0.0, time stamp: 0x4c28a603
Faulting module name: pandaJ2534_0404_32.dll, version: 1.0.0.1, time stamp: 0x59e692bd
Exception code: 0xc0000005
Fault offset: 0x00009dd7
Faulting process id: 0x16a0
Faulting application start time: 0x01d3671b8cecd37b
Faulting application path: C:\Program Files (x86)\DrewTech\DrewTech_2534-1\DrewTech_J2534-1.exe
Faulting module path: C:\Program Files (x86)\comma.ai\panda\pandaJ2534_0404_32.dll
Report Id: 4e2786ca-5b9b-4db7-9f66-a8e2af4ed032
Faulting package full name: 
Faulting package-relative application ID: 
```

Thanks!

**Pull request merged**
